spring.application.name=meditrack
jwt.secret=meditrack-jwt-secret-key-para-firma-hs256-debe-tener-al-menos-256-bits-ok
jwt.expiration=28800000
spring.profiles.active=local
server.port=${PORT:8080}
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
